cmd_drivers/gpu/pvr/pdump.o := arm-linux-gcc -Wp,-MD,drivers/gpu/pvr/.pdump.o.d  -nostdinc -isystem /opt/FriendlyARM/toolschain/4.5.1/lib/gcc/arm-none-linux-gnueabi/4.5.1/include -I/workplace/linux-3.0.8/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-s5pv210/include -Iarch/arm/plat-s5p/include -Iarch/arm/plat-samsung/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -fomit-frame-pointer -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Wdeclaration-after-statement -Wpointer-arith -Wmissing-format-attribute -Wno-format-zero-length -Wmissing-prototypes -Wstrict-prototypes -Wno-unused-parameter -Wno-sign-compare -Werror -fno-strict-aliasing -Wno-pointer-arith -Os -DLINUX -D__linux__ -DANDROID -Idrivers/gpu/pvr -DSUPPORT_SGX_NEW_STATUS_VALS -DSUPPORT_SGX_HWPERF -DSYS_USING_INTERRUPTS -DPVR_SECURE_HANDLES -DTRANSFER_QUEUE -DSUPPORT_SGX -DSUPPORT_HW_RECOVERY -DLDM_PLATFORM -DPVR_LINUX_USING_WORKQUEUES -DPVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE -DPVR_LINUX_TIMERS_USING_WORKQUEUES -DSYS_CUSTOM_POWERLOCK_WRAP -DSUPPORT_MEMINFO_IDS -DSYS_SGX_ACTIVE_POWER_LATENCY_MS=100 -DPVRSRV_MODNAME="\"pvrsrvkm\"" -Idrivers/gpu/pvr/sgx -DSUPPORT_GET_DC_BUFFERS_SYS_PHYADDRS -DPVR_LDM_DRIVER_REGISTRATION_NAME="\"pvrsrvkm\"" -DPVR_BUILD_TYPE="\"release\"" -DRELEASE -DPVRSRV_NEED_PVR_DPF -DPVRSRV_NEED_PVR_ASSERT -DSUPPORT_PERCONTEXT_PB -DSUPPORT_SGX_LOW_LATENCY_SCHEDULING -DSUPPORT_ACTIVE_POWER_MANAGEMENT -DPVRSRV_USSE_EDM_STATUS_DEBUG -DPVRSRV_DUMP_MK_TRACE -DPVR_BUILD_DIR="\"smdkc110_android\"" -Idrivers/gpu/pvr/s5pc110 -DDISPLAY_CONTROLLER=s3c_lcd -DSLSI_S5PC110 -DSGX540 -DSUPPORT_SGX540 -DSGX_CORE_REV=120    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(pdump)"  -D"KBUILD_MODNAME=KBUILD_STR(pvrsrvkm)" -c -o drivers/gpu/pvr/pdump.o drivers/gpu/pvr/pdump.c

source_drivers/gpu/pvr/pdump.o := drivers/gpu/pvr/pdump.c

deps_drivers/gpu/pvr/pdump.o := \

drivers/gpu/pvr/pdump.o: $(deps_drivers/gpu/pvr/pdump.o)

$(deps_drivers/gpu/pvr/pdump.o):
